apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: pca9685
  type: NodePort
  ports:
    - 
      port: 9090
      nodePort: 30000
      name: my-port-9090

    - 
      port: 7890
      nodePort: 30001
      name: my-port-9010

    